name: Build and Deploy Swift-DocC Site

on:
  push:
    branches: [ "translation-tr" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare Site Content and Redirect
        run: |
          mkdir -p ./_site/swift-book
          xcrun docc convert TSPL.docc \
          --output-path ./_site/swift-book \
          --transform-for-static-hosting \
          --hosting-base-path swift-book \
          --fallback-display-name "Swift Programlama Dili"
          echo '<!DOCTYPE html><html lang="tr"><head><title>Yönlendiriliyor...</title><meta http-equiv="refresh" content="0; url=./documentation/the-swift-programming-language/" /></head><body><p>Lütfen bekleyin, kitap sayfasına yönlendiriliyorsunuz...</p></body></html>' > ./_site/swift-book/index.html
          mkdir -p ./_site/swift-book/documentation
          echo '<!DOCTYPE html><html lang="tr"><head><title>Yönlendiriliyor...</title><meta http-equiv="refresh" content="0; url=./the-swift-programming-language/" /></head><body><p>Lütfen bekleyin, kitap sayfasına yönlendiriliyorsunuz...</p></body></html>' > ./_site/swift-book/documentation/index.html
          echo "docs.swift.org.tr" > ./_site/CNAME
          touch ./_site/index.html

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4